/*
   Copyright 2012 the go.wde authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package wde

type Glyph string
const (
  KeyFunction Glyph = "function"
  KeyLeftSuper Glyph = "left_super"
  KeyRightSuper Glyph = "right_super"
  KeyLeftAlt Glyph = "left_alt"
  KeyRightAlt Glyph = "right_alt"
  KeyLeftControl Glyph = "left_control"
  KeyRightControl Glyph = "right_control"
  KeyLeftShift Glyph = "left_shift"
  KeyRightShift Glyph = "right_shift"
  KeyUpArrow Glyph = "up_arrow"
  KeyDownArrow Glyph = "down_arrow"
  KeyLeftArrow Glyph = "left_arrow"
  KeyRightArrow Glyph = "right_arrow"
  KeyInsert Glyph = "insert"
  KeyTab Glyph = "tab"
  KeySpace Glyph = "space"
  KeyA Glyph = "a"
  KeyB Glyph = "b"
  KeyC Glyph = "c"
  KeyD Glyph = "d"
  KeyE Glyph = "e"
  KeyF Glyph = "f"
  KeyG Glyph = "g"
  KeyH Glyph = "h"
  KeyI Glyph = "i"
  KeyJ Glyph = "j"
  KeyK Glyph = "k"
  KeyL Glyph = "l"
  KeyM Glyph = "m"
  KeyN Glyph = "n"
  KeyO Glyph = "o"
  KeyP Glyph = "p"
  KeyQ Glyph = "q"
  KeyR Glyph = "r"
  KeyS Glyph = "s"
  KeyT Glyph = "t"
  KeyU Glyph = "u"
  KeyV Glyph = "v"
  KeyW Glyph = "w"
  KeyX Glyph = "x"
  KeyY Glyph = "y"
  KeyZ Glyph = "z"
  Key1 Glyph = "1"
  Key2 Glyph = "2"
  Key3 Glyph = "3"
  Key4 Glyph = "4"
  Key5 Glyph = "5"
  Key6 Glyph = "6"
  Key7 Glyph = "7"
  Key8 Glyph = "8"
  Key9 Glyph = "9"
  Key0 Glyph = "0"
  KeyPad1 Glyph = "1"
  KeyPad2 Glyph = "2"
  KeyPad3 Glyph = "3"
  KeyPad4 Glyph = "4"
  KeyPad5 Glyph = "5"
  KeyPad6 Glyph = "6"
  KeyPad7 Glyph = "7"
  KeyPad8 Glyph = "8"
  KeyPad9 Glyph = "9"
  KeyPad0 Glyph = "0"
  KeyPadSlash Glyph = "0"
  KeyPadStar Glyph = "0"
  KeyPadMinus Glyph = "0"
  KeyPadPlus Glyph = "0"
  KeyPadPeriod Glyph = "0"
  KeyBackTick Glyph = "0"
  KeyF1 Glyph = "f1"
  KeyF2 Glyph = "f2"
  KeyF3 Glyph = "f3"
  KeyF4 Glyph = "f4"
  KeyF5 Glyph = "f5"
  KeyF6 Glyph = "f6"
  KeyF7 Glyph = "f7"
  KeyF8 Glyph = "f8"
  KeyF9 Glyph = "f9"
  KeyF10 Glyph = "f10"
  KeyF11 Glyph = "f11"
  KeyF12 Glyph = "f12"
  KeyF13 Glyph = "f13"
  KeyF14 Glyph = "f14"
  KeyF15 Glyph = "f15"
  KeyMinus Glyph = "-"
  KeyPlus Glyph = "+"
  KeyLeftBracket Glyph = "["
  KeyRightBracket Glyph = "]"
  KeyBackslash Glyph = `\`
  KeySemicolon Glyph = ";"
  KeyQuote Glyph = "'"
  KeyComma Glyph = ","
  KeyPeriod Glyph = "."
  KeySlash Glyph = "/"
  KeyReturn Glyph = "return"
  KeyEscape Glyph = "escape"
  KeyNumlock Glyph = "numlock"
  KeyDelete Glyph = "delete"
  KeyBackspace Glyph = "backspace"
  KeyHome Glyph = "home"
  KeyEnd Glyph = "end"
  KeyPageUp Glyph = "page_up"
  KeyPageDown Glyph = "page_down"
)

